M48
; DRILL file {KiCad (5.99.0-10766-geeb405c196)} date Sat Jun 19 10:41:38 2021
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2021-06-19T10:41:38+04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(5.99.0-10766-geeb405c196)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0315
%
G90
G05
T1
X4.1161Y-3.3878
X4.1161Y-3.5846
T0
M30
